version: '3'
networks:
  app-tier:
    driver: bridge
services:
  todo-api:
    build: .
    networks:
      - app-tier
    ports:
      - "8010:8010"
    depends_on:
      - dbpgsql
    volumes:
      - ".:/simple-todo-api/src/app"
  dbpgsql:
    image: postgres:15
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    networks:
      - app-tier
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    depends_on:
      - todo-api
    networks:
      - app-tier
